name: meridio-vpn-gateway

services:
  vpn-gateway:
    image: vpn-gateway:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vpn-gateway
    privileged: true
    command: /init.sh
    sysctls:
      - net.ipv4.conf.all.rp_filter=2
      - net.ipv4.conf.default.rp_filter=2
    networks:
      - kind

networks:
  kind:
    name: kind
    external: true
